### PR TITLE
fixed an error in the file style.css

### PR DESCRIPTION
**Pull request by Geoelycom**

### CODE REVIEW

**Comment by Geoelycom** [comment]
Great job so far. but I can see you have failed to resolve some of the Linters errors. Always make sure all Linter errors are passing. 
Optionally you could check for these errors in your local machine by setting this check-up, you can refer to HTML, CSS, Linters lesson on how to do this.

**Comment by Geoelycom** [comment]
Congratulations you have done a great job. I Can see you have resolved the Linter errors.

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
Hi @Geoelycom,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

- It's super important that we always state the reasons WHY we want students to make a certain change because it gives them more insights on why your requested change is a better approach.

- Going forward, I will suggest that we always cultivate the culture of using GitHub inline comments as it makes CR seamless and easy for error tracking and follow-up for both CRs and students. 
> To do this, make sure you go to the "File changes" tab and use the "Start a review" button for your first review comment.

- When asking students to "refer to HTML, CSS, Linters lesson", I think it will be best if you can provide the link as well, this will really be helpful to the student.

-  I will suggest you always use the "Request Changes" template for your code reviews as it will help keep your CR organized and consistent across all reviews.
> A typical example is what I am using for this review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Geoelycom** [comment]
Hi thanks for the comment, but a lot of the informations seem's clustered and making it hard for me to understand what you want me to do. Can you please in a word what i need to do get the project approved. a new review with a review template or what. I do need this clarification please.

**Comment by Geoelycom** [comment]
How do i access the review template??

**Comment by Geoelycom** [comment]
> Hi @Geoelycom,
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * It's super important that we always state the reasons WHY we want students to make a certain change because it gives them more insights on why your requested change is a better approach.
> * Going forward, I will suggest that we always cultivate the culture of using GitHub inline comments as it makes CR seamless and easy for error tracking and follow-up for both CRs and students.
> 
> > To do this, make sure you go to the "File changes" tab and use the "Start a review" button for your first review comment.
> 
> * When asking students to "refer to HTML, CSS, Linters lesson", I think it will be best if you can provide the link as well, this will really be helpful to the student.
> * I will suggest you always use the "Request Changes" template for your code reviews as it will help keep your CR organized and consistent across all reviews.
> 
> > A typical example is what I am using for this review.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello, I stated the reason why I needed changes in the first review which was (linter errors). adding to my previous comments, please this whole information seems to be too much worded and I'm having a hard time understanding them. do get back to me with some clarifications on what I actually need to do, the request changes template, how do I get it? Also, I can't see the start a review button when I go to the file changed tab. Please if you can check this swiftly for me as I'm running out of time to do other important tasks.

**Comment by acushlakoncept** [comment]
Hi @Geoelycom,

1. Your first point " I can see you have failed to resolve some of the Linters errors. Always make sure all Linter errors are passing."  Here you have successfully pointed out the error that needs to correct ✔️  But you have not told the students why fixing linters errors is important to fix. The point is when requesting for a change, always try to give the student WHY the change is neccessary.

**Comment by acushlakoncept** [comment]
> How do I access the review template??
- A typical example is what I am using for this review.

You can access this from the notion page. 

```markdown
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

```

**Comment by acushlakoncept** [comment]
If there is any point that you still find hard to understand, please do not hesitate to reply to this thread.

**Comment by Geoelycom** [comment]
> Hi @Geoelycom,
> 
> 1. Your first point " I can see you have failed to resolve some of the Linters errors. Always make sure all Linter errors are passing."  Here you have successfully pointed out the error that needs to correct ✔️  But you have not told the students why fixing linters errors is important. The point is when requesting a change, always try to give the student WHY the change is necessary.

Okay thank you. But that's not all sir. Some of my questions are unanswered, how do I get the Template you suggest I use, do i copy the one you used to review my mine, or there is a way I can get it. Another point, I can't seem to see the Review button, i can only see review changes button when I click on the files change tab. Is that what you are refferring to? Please I need your assistance with this. Thank you.

**Comment by acushlakoncept** [comment]
Yes, when you click on the files changed tab.

I added a copy of the template in one of my comments, also see if you have access to this [link](https://www.notion.so/Code-Reviewers-2-0-training-8h-552776f7a8b2465e9710742eb5324f47#a53ac97589904fc08abc6699cb97b9ff).

**Review by Geoelycom — COMMENTED** [review]
Hi @Geoelycom

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._
<ul>I can see you have failed to resolve the Linters errors in your code. Linters are put in place to help you catch programming mistakes why you concentrate on what matters most solving problems.</ul>
<ul>Always have a descriptive name for your branch.</ul>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by acushlakoncept — APPROVED** [review]
Hi @Geoelycom, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Geoelycom** [comment]
> Hi @Geoelycom,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

whoops, that was a tough one.!!

**Pull request merged**
