### PR TITLE
Checking for linter changes

### PR DESCRIPTION
**Pull request by Geoelycom**

### CODE REVIEW

**Comment by Geoelycom** [comment]
Great Job, but a little more work needed.
According to the project requirements, I think you should resolve the Linters errors, as some of the rules are not passing.
Also, I suggest you check to make sure that you are using a semantic tag in your index.html file.
Try Looking at the Header, there are some better tags you can use in place of the current one. Visit MDN  for documentation or reach out to a team member.

**Comment by Geoelycom** [comment]
This Looks very good. I can see all the work you have put in to make sure all checks passed. you can go ahead merge the changes now.

**Review by Spayco — COMMENTED** [review]
Hi @Geoelycom, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a merged PR, and without any of the steps required by [the project lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Geoelycom** [comment]
The project requirements was for me to give myself a review and go through the process of reviewing a project. After doing that, you should check if the review i gave myself was okay. I had the impression that after giving myself the review, I have to merge as that was exactly what i did in my last project. Please clarify this for me.

**Comment by Spayco** [comment]
> The project requirements was for me to give myself a review and go through the process of reviewing a project. After doing that, you should check if the review i gave myself was okay. I had the impression that after giving myself the review, I have to merge as that was exactly what i did in my last project. Please clarify this for me.

Hi again, no, you don't need to merge it, you have to review your project, and then we gonna review the review, here's an example by one of the other student: https://github.com/miguelesco/Review-your-project-from-trials/pull/1

please let me know if you have any other questions! I'll be happy to help

**Comment by Geoelycom** [comment]
Okay, so I do I create a new pull request or what, or is there a way I can open an already closed one thank you.

**Comment by Spayco** [comment]
@Geoelycom yes create a new PR, you can reopen a _closed_ PR, but this is a **merged** PR, so you can't open it again

**Comment by Geoelycom** [comment]
> @Geoelycom yes create a new PR, you can reopen a _closed_ PR, but this is a **merged** PR, so you can't open it again

Okay thanks. I have to create a new PR, give myself a review and submit it for a rereview right? I need to get all the informations sorry

**Comment by Spayco** [comment]
> > @Geoelycom yes create a new PR, you can reopen a _closed_ PR, but this is a **merged** PR, so you can't open it again
> 
> Okay thanks. I have to create a new PR, give myself a review and submit it for a rereview right? I need to get all the informations sorry

exactly! best of luck 😄

**Comment by Geoelycom** [comment]
Okay thanks for clarification. Would do this tomorrow as its late now.

**Pull request merged**
